from setuptools import setup, find_packages

setup(name='tinyllm',
      version='0.1.1',
      description='Development and management infrastructure for LLM applications',
      packages=find_packages(),
      install_requires=[
          'astor',
          'click',
          'tenacity',
          'langfuse',
          'litellm',
          'openai',
          'numpydoc',
          'pathspec',
          'pgvector',
          'psutil',
          'psycopg2-binary',
          'pydantic==1.10.7',
          'pytest',
          'pyyaml',
          'sqlalchemy',
          'tiktoken',
          'typing-extensions==4.5.0',
          'uuid',
          'fuzzywuzzy'
      ],
      author='Othmane Zoheir',
      author_email='othmane@rumorz.io',
      url='')
